name       : python-anyascii
version    : 0.3.2
release    : 2
source     :
    - https://files.pythonhosted.org/packages/source/a/anyascii/anyascii-0.3.2.tar.gz : 9d5d32ef844fe225b8bc7cba7f950534fae4da27a9bf3a6bea2cb0ea46ce4730
license    : ISC
homepage   : https://github.com/anyascii/anyascii
component  : programming.python
summary    : Unicode to ASCII transliteration
description: |
    AnyAscii provides ASCII-only replacement strings for practically all Unicode characters. Text is converted character-by-character without considering the context. The mappings for each script are based on popular existing romanization systems. Symbolic characters are converted based on their meaning or appearance. All ASCII characters in the input are left unchanged, every other character is replaced with printable ASCII characters. Unknown characters and some known characters are replaced with an empty string and removed.
build      : |
    %python3_setup
install    : |
    %python3_install
